services:
  postgres:
    image: postgres:16
    container_name: fit-route-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fitroute
      POSTGRES_PASSWORD: fitroute
      POSTGRES_DB: fitroute
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
